files:
  - source: /txt for gamedata/csv/Файли гри/
    translation: /translations/%two_letters_code%/%original_path%/%original_file_name%
    first_line_contains_header: 1
    scheme: 'identifier,source_or_translation'
