name: EsoUA_release

on:
  # Trigger the pipeline only in release branch.
  push:
    branches:
      - 'workflow-test'
    paths:
      # Run the pipeline when only `package.json` file is modified.
      - 'package.json'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  upload-addon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - run: npm run uploadAddOn
        env:
          ESOUI_PASSWORD_TEST: ${{ env.ESOUI_PASSWORD_TEST }}
          ESOUI_USERNAME_TEST: ${{ env.ESOUI_USERNAME_TEST }}
