name: EsoUA_main

on:
  # Trigger the pipeline only in main branch.
  push:
    branches:
      - 'main'
    paths:
      # Run the pipeline when only `UkrainianScrollsOnline.txt` file is modified.
      - 'UkrainianScrollsOnline/UkrainianScrollsOnline.txt'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  merge-to-release-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'release'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
