name: EsoUA_common

on:
  # Trigger the pipeline only in every branch except main and release.
  pull_request:
    branches:
      - 'main'
    #   # Run the pipeline when only `UkrainianScrollsOnline.(lua|txt)` files are modified.
    #   - 'UkrainianScrollsOnline/UkrainianScrollsOnline.lua'
    #   - 'UkrainianScrollsOnline/UkrainianScrollsOnline.txt'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verify-changed-files:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: dorny/paths-filter@v2
        id: verify_changed_files
        with:
          filters: |
            lua:
              - 'UkrainianScrollsOnline/UkrainianScrollsOnline.lua'
            txt:
              - 'UkrainianScrollsOnline/UkrainianScrollsOnline.txt'
      - if: steps.changes.outputs.lua == 'true' && steps.changes.outputs.txt == 'true'
        run: echo Matched
