name: EsoUA_release

on:
  # # Trigger this pipeline only after EsoUA_main pipeline finished successfully.
  workflow_run:
    workflows: ['EsoUA_main']
    types:
      - completed
  # Trigger the pipeline only in release branch.
  push:
    branches:
      - 'release'
    paths:
      # Run the pipeline when only `UkrainianScrollsOnline.txt` file is modified.
      - 'UkrainianScrollsOnline/UkrainianScrollsOnline.txt'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  upload-addon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sh upload-addon.sh
        env:
          ESOUI_API_TOKEN: ${{ secrets.ESOUI_API_TOKEN }}
          ESOUI_ID: ${{ secrets.ESOUI_ID }}
