name: EsoUA_common

on:
  # Trigger the pipeline only in every branch except main and release.
  pull_request:
    branches:
      - 'main'
    #   # Run the pipeline when only `UkrainianScrollsOnline.(lua|txt)` files are modified.
    #   - 'UkrainianScrollsOnline/UkrainianScrollsOnline.lua'
    #   - 'UkrainianScrollsOnline/UkrainianScrollsOnline.txt'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verify-changed-files:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: foodee/pr-includes-file-change@master
        id: verify_changed_files
        with:
          paths: ^UkrainianScrollsOnline.lua ^UkrainianScrollsOnline.txt
      - if: steps.verify_changed_files.outputs.matched == 'true'
        run: exit 0
      - if: steps.verify_changed_files.outputs.matched == 'false'
        run: exit 1
